version: '3.8'
services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.8-management-alpine
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=E3C20CE98
    ports:
        # rabbitMq instance
        - 5672:5672
        # web interface
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - microserices_network

networks:
    microserices_network:
        driver: bridge